[tool.pylint]
    [tool.pylint.messages_control]
    disable = [
        "fixme",
        "missing-docstring",
        "too-many-line",
        "too-few-public-methods",
        "too-many-instance-attributes",
    ]
    enable = [
        "unused-import",
    ]

    [tool.pylint.basic]
    good-names = "a,b,c,d,e,f,g,h,i,id,j,k,m,n,p,q,r,s,t,u,v,w,x,y,_"

[tool.pydocstyle]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D106",
    "D107",
    "D200",
    "D202",
    "D203",
    "D205",
    "D211",
    "D212",
    "D213",
    "D301",
    "D400",
]
